version: '3.8'

services:
  mongo:
    build: ./docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: kabu-memo
      TZ: Asia/Tokyo        
    ports:
      - 27017:27017
    container_name: kabu-memo-mongodb
    volumes:
      - ./docker/mongodb/initdb.d:/docker-entrypoint-initdb.d:ro