version: '3.8'

services:
  mongo:
    build: ./docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: kabu-memo
      TZ: Asia/Tokyo
    # command:
    #   - --auth
    #   - -f
    #   - /etc/mongod.conf
        
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/initdb.d:/docker-entrypoint-initdb.d:ro
    container_name: kabu-memo-mongodb